feat: #WB-3001, add reactions summary component
edificeio/edifice-ui pull request #173
Opened 2024-05-30 07:27 UTC by jcbe-ode

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Which Package changed?

Please check the name of the package you changed

- [ ] Components
- [ ] Core
- [ ] Icons
- [ ] Hooks

## Has the documentation changed?

- [ ] Storybook

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [ ] New feature (MINOR)
- [ ] Breaking change (MAJOR)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2024-05-30 07:28 UTC, jcbe-ode commented
Ajout des icônes pour les réactions => j'en ai profité pour "corriger" les exports de typings du package.json
@ccreusat c'est bon pour toi ?

2024-05-30 07:57 UTC, ccreusat commented
@jcbe-ode je regarde ça ASAP, mais c'est un peu le 🔥 pour le moment mais quelques commentaires :
- le nommage des icones ne me va pas: voir sur le figma les noms qui sont en "français", et les mettre en "anglais" > je vois avec Laura et Simon
- qui t'as fourni les SVGs ?
- le composant `ReactionSummary` n'est pas encore fait, d'où la DRAFT ? Est-ce qu'on est sur que ce sera réutilisé ailleurs ? Mesure d'audience doit être portée sur d'autres applications ?

merci

2024-05-30 08:37 UTC, jcbe-ode commented
>     * le nommage des icones ne me va pas: voir sur le figma les noms qui sont en "français", et les mettre en "anglais" > je vois avec Laura et Simon
OK merci

>     * qui t'as fourni les SVGs ?
Je les ai exportés depuis Library_Web, mais maintenant que tu le soulignes, ils auraient dû être trouvés dans le drive DesignToDev

>     * le composant `ReactionSummary` n'est pas encore fait, d'où la DRAFT ? Est-ce qu'on est sur que ce sera réutilisé ailleurs ? Mesure d'audience doit être portée sur d'autres applications ?
Oui il est en court de dev.
Oui, il sera utilisé dans d'autres applis à terme : 

> “Mesure d’audience” est un composant transverse qui est composé de 2 éléments : 
> *    Les réactions
>  *  Les vues
>
> Ce composant permet d’avoir un retour pour les enseignants. 
> Le composant “Mesure d’audience” peut être intégré dans les différentes applications. (...)

2024-05-31 08:25 UTC, ccreusat commented on packages/react/ui/src/core/useReactionIcons/useReactionIcons.tsx
@jcbe-ode j'aurai plutôt regrouper le hook avec le composant, comme pour les modales par exemple car je trouve pas forcément que c'est "core", tu l'utiliseras pas comme tu utiliserais le hook `useUser` qui est global. Là c'est propre à Reaction..
Par exemple, pour la modale de partage on a : 

```
ShareModal/ShareModal.tsx
ShareModal/hook/useShare.tsx
```
donc j'aurai bien tout regrouper

```
ui/src/components/Reaction/Reaction.tsx
ui/src/components/Reaction/useReactionIcons.tsx
```

d'ailleurs, est-ce que le nommage "Widget" est correct , si c'est un vrai "widget", (comme ceux de timeline, il faudrait qu'il soit dans le "futur" package "widget"

👍🏼

2024-05-31 08:25 UTC, ccreusat commented on packages/react/ui/src/core/useReactionIcons/useReactionIcons.tsx
> +      case "REACTION_1":
@jcbe-ode je sais pas ce qui vient du backend, mais le type de reaction, devrait correspondre au bon nommage : thanks, good, interesting, ..

2024-05-31 08:25 UTC, ccreusat commented on vite.config.ts
> +      ],
👍🏼

2024-05-31 08:25 UTC, ccreusat commented on packages/react/ui/vite.config.ts
> +        "@edifice-ui/icons/reactions",
👍🏼

2024-05-31 08:25 UTC, ccreusat commented on packages/react/ui/src/types/index.ts
> +export {
@jcbe-ode c'est le composant Reaction (son dossier) qui devrait exporter ses types, comme les autres composants, pourquoi le mettre là (si j'ai raté un truc)

2024-05-31 08:25 UTC, ccreusat commented on packages/react/ui/src/components/Reaction/ReactionWidget.tsx
> +    <>
le composant affiche la liste avec le counter et aussi le bouton pour ouvrir le dropdown, c'est ça ?

2024-05-31 08:25 UTC, ccreusat commented on packages/react/ui/package.json
> +    "@edifice-ui/icons": "workspace:*",
@jcbe-ode c'est pas bon, pour la `peerDependencies`, c'est bien '*', et pour la `devDependencies`, pas la peine de remettre `workspace:*` car lerna remplace par la dernière version à chaque fois 😅

2024-05-31 08:25 UTC, ccreusat commented on packages/react/icons/vite.config.ts
> +        reactions: resolve(__dirname, "src/reactions/index.ts"),
👍🏼

2024-05-31 08:25 UTC, ccreusat commented on packages/react/icons/src/reactions/index.ts
> +export { default as Reaction1Circle } from "./Reaction1Circle";
à revoir avec le bon nommage fourni par le design

2024-05-31 12:44 UTC, jcbe-ode commented
En pause le temps de traiter des hotfixs

2024-06-02 11:41 UTC, ccreusat commented on packages/react/icons/assets/reactions/great_counter.svg
la convention de nommage est avec des - (ex: `great-counter.svg`), merci 😉

2024-06-03 09:21 UTC, jcbe-ode commented on packages/react/ui/src/core/useReactionIcons/useReactionIcons.tsx
> +      case "REACTION_1":
Les codes envoyés par le backend sont génériques (REACTION_1, REACTION_2...)
Et comme il faut faire un mapping qqpart, c'est fait dans ce hook.

2024-06-03 09:30 UTC, jcbe-ode commented on packages/react/ui/src/types/index.ts
> +export {
C'est les types tels que définis par le backend.
Mais comme on ne les utilisera qu'ici, OK avec toi :+1:

2024-06-03 09:55 UTC, jcbe-ode commented on packages/react/ui/package.json
> +    "@edifice-ui/icons": "workspace:*",
ah ok merci, je trouvais ça bizarre aussi !

2024-06-03 10:09 UTC, jcbe-ode commented on packages/react/ui/src/core/useReactionIcons/useReactionIcons.tsx
* Les composants pour gérer les vues et les réactions sont plutôt transverses et "évolués", comme la ShareModal.
=> je déplace le tout dans le dossier "common"

* Le suffixe Widget a déjà été supprimé car il me choquait aussi.

2024-06-26 09:38 UTC, ccreusat commented on packages/react/ui/src/core/useReactionIcons/useReactionIcons.tsx
> +      case "REACTION_1":
Ah ouais ça renvoie ça ? Crado

2024-06-26 09:46 UTC, ccreusat commented on packages/bootstrap/scss/components/_index.scss
> +@forward "reaction-summary";
@jcbe-ode a regrouper avec le dossier de @Romu-C  pour avoir un bloc commun (à voir une fois tout merger peut être pour fignoler)

2024-06-26 09:47 UTC, ccreusat commented on packages/react/icons/package.json
> +      "types": "./dist/reactions/index.d.ts",
@jcbe-ode @Romu-C idem, voir commentaire sur slack et PR de Romuald pour regrouper tout ça

2024-06-26 09:47 UTC, ccreusat commented on packages/react/icons/vite.config.ts
> +        reactions: resolve(__dirname, "src/reactions/index.ts"),
@jcbe-ode à regrouper idem si ok

2024-06-26 09:47 UTC, ccreusat commented on packages/react/ui/package.json
> +    "@edifice-ui/icons": "workspace:*",
@jcbe-ode comme pour les PRs @Romu-C , pas besoin de renommer

2024-06-26 09:48 UTC, ccreusat commented on packages/react/ui/package.json
> +    "@edifice-ui/icons": "workspace:*",
@jcbe-ode , ne pas toucher, et laisser "*"

2024-06-26 09:48 UTC, ccreusat commented on packages/react/ui/src/components/Reaction/ReactionSummary.stories.tsx
idem à voir pour tout regrouper avec les vues

2024-06-26 09:49 UTC, ccreusat commented on packages/react/ui/src/components/Reaction/ReactionSummary.tsx
> +  const handleReactionClick = (reactionType: ReactionType) => {
`handleReactionOnClick`

2024-06-26 09:49 UTC, ccreusat commented on packages/react/ui/src/components/Reaction/ReactionTypes.ts
> +export type ReactionType =
@jcbe-ode a mettre comme les autres composants les types/interfaces dans les composants et les exporter stp

2024-06-26 09:51 UTC, ccreusat commented on packages/react/ui/src/components/Reaction/hook/useReactions.tsx
> +  const _get = odeServices.http().get;
ça fonctionne pas de destructurer ?? 🤔 

```
const {get, putJson, ...} = odeServices.http()
```

2024-06-26 09:54 UTC, ccreusat commented on packages/react/ui/src/components/Reaction/hook/useReactions.tsx
ton fichier n'exporte pas de JSX, pas besoin de l'extension `tsx`

2024-06-26 09:55 UTC, ccreusat requested changes
a prendre les commentaires en compte stp

2024-06-27 16:08 UTC, merged