feat(mediacentre): [#MED-264] add icon Mediacentre
edificeio/edifice-ui pull request #175
Opened 2024-05-31 10:25 UTC by qperie

# Description

Add new dedicated icon for Mediacentre

## Which Package changed?

- [ ] Components
- [ ] Core
- [x] Icons
- [ ] Hooks

## Has the documentation changed?

- [ ] Storybook

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [x] New feature (MINOR)
- [ ] Breaking change (MAJOR)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2024-05-31 13:12 UTC, ccreusat requested changes

2024-05-31 13:12 UTC, ccreusat commented on packages/bootstrap/scss/abstracts/_icons.scss
> +    "neo": #2029b6,
@qperie il y a une variable pour cette couleur : `$indigo`

2024-05-31 13:12 UTC, ccreusat commented on packages/react/icons/assets/apps/mediacentre.svg
<img width="634" alt="Capture d’écran 2024-05-31 à 15 12 12" src="https://github.com/edificeio/edifice-ui/assets/9531648/da9d54ed-3ad5-43eb-a245-35088814db80">

l'icone ajoutée n'est pas bonne, merci de la corriger et de modifier les fichiers en conséquence 😉

2024-06-03 08:01 UTC, qperie commented on packages/react/icons/assets/apps/mediacentre.svg
Je m'y connais pas énormément en SVG mais l'intérêt n'est pas justement que la taille est modulable à volonté sans distorsion ? Tu veux que le logo soit de taille à forcément passer dans un viewPort de 125x150px ? Ou que je modifie les valeurs du viewPort pour qu'on voit l'icône dans sont entièreté ?

2024-06-03 11:57 UTC, ccreusat commented on packages/react/icons/assets/apps/mediacentre.svg
@qperie l'icone devrait être visible dans l'image. y'a un viewBox de 24x24 à respecter, tu peux utiliser un service comme svgomg pour voir que l'icone s'affiche mal https://jakearchibald.github.io/svgomg/

2024-06-21 08:17 UTC, ccreusat commented on packages/react/icons/assets/apps/mediacentre.svg
@qperie c'est pas bon, l'icone est invisible .. vous pouvez tester les icones avec storybook en local une fois l'icone buildée avec `pnpm run docs` -> section "App and Connectors Icons"

2024-06-25 13:52 UTC, merged