feature(ui): #WB-2998 views counter
edificeio/edifice-ui pull request #201
Opened 2024-06-25 15:28 UTC by Romu-C

# Description

Add new component used for audience purpose `ViewsCounter`

## Which Package changed?

Please check the name of the package you changed

- [ ] Components
- [ ] Core
- [ ] Icons
- [ ] Hooks

## Has the documentation changed?

- [x] Storybook

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [x] New feature (MINOR)
- [ ] Breaking change (MAJOR)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2024-06-26 07:25 UTC, jcbe-ode commented on packages/react/ui/src/components/Views/ViewsCounter.tsx
> +  const handleOnClick = () => {
A voir ce qu'en pense Clément, mais autant déserialiser `onClick` en le renommant `handleOnClick` directement, et supprimer cette lambda (=> allègement du code et de la mémoire du navigateur).

2024-06-26 07:26 UTC, jcbe-ode commented on packages/react/ui/src/components/Views/hooks/ViewService.ts
Pourquoi est-ce une `class`  plutôt qu'un hook ?

2024-06-26 08:09 UTC, jcbe-ode reviewed
Voir questions en commentaire

2024-06-26 08:25 UTC, Romu-C commented on packages/react/ui/src/components/Views/hooks/ViewService.ts
Pour pouvoir utilise le service dans le code de blog (ou autre application) et l'appeler via ReatQuery
Du coté blog j'aurais quelque chose comme
```
/**
 * Load the views counter of a list of posts
 * @param ressourceIds list of post ids
 * @returns views counters
 */
export function loadPostsViewsCounter(ressourceIds: string[]) {
  const viewService = new ViewsService("blog", "post");
  return checkHttpError<ViewsCounters>(
    viewService.getViewsCounters(ressourceIds),
  );
}

export const postsViewsCounterQuery = (ressourceIds: string[]) => {
  return {
    queryKey: blogQueryKeys.postsViewsCounter(ressourceIds),
    queryFn: () => loadPostsViewsCounter(ressourceIds),
  };
};

const query = useQuery(postsViewsCounterQuery(resourceIds));
```

Qui me permettra de récupérer les info tout en profitant du système de cache mis en place. 
Ça peut se changer mais j'arrive pas à voir l'avantage de le mettre en hook hormis le fait de se couper le fait de l'appeler dans un loader.

2024-06-26 09:07 UTC, ccreusat commented on packages/bootstrap/assets/images/emptyscreen/illu-fil-de-nouveautes.svg
nom du fichier en anglais stp

2024-06-26 09:08 UTC, ccreusat commented on docs/stories/icons/Icons.Views.mdx
ne faire une story que si le composant peut être réutilisé de façon indépendante dans des applis. si le composant fait parti d'un autre composant, ne pas faire une story dédiée

2024-06-26 09:08 UTC, ccreusat commented on docs/stories/icons/Icons.Views.stories.js
fichier avec extension .tsx

2024-06-26 09:12 UTC, ccreusat commented on packages/react/icons/package.json
@Romu-C je crois que @jcbe-ode avait déjà fait ça sur une branche, vous mélangez pas les pinceaux, fusionnez ça svp

2024-06-26 09:13 UTC, ccreusat commented on packages/react/ui/package.json
> +    "@edifice-ui/icons": "workspace:*",
@Romu-C pas besoin de modifier à chaque fois, c'est lerna qui le fait

2024-06-26 09:13 UTC, ccreusat commented on packages/react/ui/package.json
> +    "@edifice-ui/icons": "workspace:*",
@Romu-C déjà prévenu, ne pas modifier celui là!!! ⚠️ il faut laisser "*"

2024-06-26 09:14 UTC, ccreusat commented on packages/react/ui/src/components/Views/ViewsCounter.tsx
> +      <See />
Pourquoi l'icone n'est pas passé via la props du Bouton ? `rightIcon`?

2024-06-26 09:14 UTC, ccreusat commented on packages/react/ui/src/components/Views/hooks/ViewService.ts
> +export class ViewsService {
@Romu-C ViewService ? Ca devrait être un hook réutilisable pour mesure d'audience, ni une class, mais bien un hook, nommé `useViews` ?

2024-06-26 09:15 UTC, ccreusat commented on packages/react/ui/src/components/Views/models/Views.ts
> +export type ViewsDetail = {
@Romu-C , non, si tu regardes les autres composants, les types sont dans les composants, et exportés. A bien respecter stp

2024-06-26 09:15 UTC, ccreusat requested changes
prendre en compte tous les commentaires stp

2024-06-26 12:27 UTC, jcbe-ode commented on docs/stories/icons/Icons.Views.mdx
Du coup faut supprimmer ce fichier ? Je ne comprends pas la notion de composant pour les icones

2024-06-26 12:28 UTC, jcbe-ode commented on docs/stories/icons/Icons.Views.stories.js
t'es sûr ? Les autres `stories` du dossier sont en js

2024-06-26 13:34 UTC, jcbe-ode commented on docs/stories/icons/Icons.Views.stories.js
Stories supprimées, à remettre en fin de dev (ne fonctionnent bizarrement pas dans storybook)

2024-06-26 13:35 UTC, jcbe-ode commented on packages/react/ui/package.json
> +    "@edifice-ui/icons": "workspace:*",
On en a besoin pour le dev en local, quand on change la lib d'icones; sinon on ne parvient pas à les voir dans storybook

2024-06-26 15:06 UTC, jcbe-ode commented on packages/react/ui/src/components/Views/hooks/ViewService.ts
> +export class ViewsService {
Du coup, le service est passé côté `client` comme discuté.

2024-06-26 15:08 UTC, merged

2024-06-27 07:30 UTC, ccreusat commented on packages/client/src/ts/audience/interface.ts
> +  [ressourceId: string]: number;
@jcbe-ode j'avais pas vu, mais ca devrait être `resourceId`

2024-06-27 07:36 UTC, jcbe-ode commented on packages/client/src/ts/audience/interface.ts
> +  [ressourceId: string]: number;
bien vu, je corrige avec la prochaine PR