feature(ui): #WB-2999 views modal
edificeio/edifice-ui pull request #202
Opened 2024-06-25 15:31 UTC by Romu-C

# Description

Add new component for audience purpose `ViewsModal`

## Which Package changed?

Please check the name of the package you changed

- [x] Components
- [ ] Core
- [ ] Icons
- [ ] Hooks

## Has the documentation changed?

- [x] Storybook

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [x] New feature (MINOR)
- [ ] Breaking change (MAJOR)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2024-06-26 07:30 UTC, jcbe-ode commented on packages/react/ui/src/components/Views/ViewsModal.tsx
> +    <Modal id="ViewsModal" isOpen={isOpen} onModalClose={handleOnCancel}>
un `id` un dur, ça ne posera pas de soucis ? S'il y a plusieurs modales sur la même page, pour l'accessibilité...

2024-06-26 08:06 UTC, jcbe-ode commented on packages/react/ui/src/components/Views/ViewsModal.tsx
> +  const handleOnCancel = () => {
même commentaire que dans la PR précédente

2024-06-26 08:31 UTC, Romu-C commented on packages/react/ui/src/components/Views/ViewsModal.tsx
> +    <Modal id="ViewsModal" isOpen={isOpen} onModalClose={handleOnCancel}>
Comme tu le dis on aura jamais 2 modal en même temps et jusqu'à maintenant les id des modals était en dur 
(exemple ShareModal ou PublishModal) après oui je peux mais un id plus dynamic mais pas sur que ça soit utile

2024-06-26 08:43 UTC, jcbe-ode commented on packages/react/ui/src/components/Views/ViewsModal.tsx
> +    <Modal id="ViewsModal" isOpen={isOpen} onModalClose={handleOnCancel}>
En effet laisse comme ça, je vais faire pareil avec la modale des réactions mais je trouve ça bizarre :grinning:

2024-06-26 09:20 UTC, ccreusat commented on packages/bootstrap/package.json
> +    "watch:react": "sass --watch --style compressed --load-path=node_modules/ --no-source-map scss/index.scss ../../public/assets/themes/edifice-bootstrap/index.css",
top merci! lucien me l'avait remonté, je voulais le faire 👍🏼

2024-06-26 09:20 UTC, ccreusat commented on packages/bootstrap/scss/components/views/_views-detail.scss
> +.views-detail-line {
@Romu-C tu peux même regrouper dans un sélecteur `.views-detail { & ..., &...}`

2024-06-26 09:21 UTC, ccreusat commented on packages/react/ui/src/components/Views/ViewsModal.stories.tsx
> +  title: "Components/Views modal",
@Romu-C peut regrouper dans un group "views / mesure d'audience` pour que tout soit ensemble. `Components/Views/...`

2024-06-26 09:23 UTC, ccreusat commented on packages/react/ui/src/components/Views/ViewsModal.tsx
> +import { ViewsDetail } from "./models/Views";
bouger les types dans le composant

2024-06-26 09:23 UTC, ccreusat commented on packages/react/ui/src/components/Views/ViewsModal.tsx
> +          <div className="d-flex align-items-center views-detail-line p-8 mb-12 gap-12 ">
@Romu-C j'pense que ça vaut le coup de faire des sous-composants propres pour organiser tout ça stp

2024-06-26 09:25 UTC, ccreusat commented on packages/react/ui/src/components/Views/ViewsModal.tsx
> +            {viewsDetail.totalUniqueViews !== undefined && (
@Romu-C ternary non ? pourquoi séparer === undefined et !== undefined .. a voir pour mettre dans une const propre

2024-06-26 09:26 UTC, Romu-C commented on packages/react/ui/src/components/Views/ViewsModal.stories.tsx
> +  title: "Components/Views modal",
Ah oui j'ai oublie je voulais le faire +1

2024-06-26 09:26 UTC, ccreusat commented on packages/react/ui/src/components/Views/ViewsModal.tsx
> +          {viewsDetail.counterDetails?.students !== 0 && (
pareil, ce sera plus clean de regrouper ça soit dans un `switch` soit dans un objet literal (objet pour mapper les composants) + sous composants

ex possible : https://github.com/opendigitaleducation/edifice-ui/blob/18bfb2b9ca0b04e9ca88e82b6b4a7a759374fc77/packages/react/ui/src/components/UploadCard/UploadCard.tsx#L82

2024-06-26 09:26 UTC, ccreusat commented on packages/react/ui/src/components/Views/index.ts
> +export { ViewsService } from "./services/ViewService";
doit être un hook

2024-06-26 09:26 UTC, ccreusat commented on packages/react/ui/src/components/Views/models/Views.ts
doit être dans le composant, et exporté

2024-06-26 09:27 UTC, ccreusat commented on packages/react/ui/src/components/Views/services/ViewService.ts
doit être un hook

2024-06-26 09:27 UTC, ccreusat requested changes
à prendre en compte les commentaires stp

2024-06-26 10:10 UTC, Romu-C commented on packages/react/ui/src/components/Views/index.ts
> +export { ViewsService } from "./services/ViewService";
bougé sur ts-client

2024-06-27 07:32 UTC, ccreusat commented on packages/react/ui/src/components/Views/ViewsModal.tsx
> +    <Modal id="ViewsModal" isOpen={isOpen} onModalClose={handleOnCancel}>
Effectivement, elles sont lazy loadés, jamais dans le DOM en même temps

2024-06-27 08:50 UTC, merged