feat(ui): #WB-3002, reactions details modal
edificeio/edifice-ui pull request #203
Opened 2024-06-26 09:00 UTC by jcbe-ode

# Description

> [Ticket WB-3002](https://edifice-community.atlassian.net/browse/WB-3002)

Il s'agit de la modale détaillant les réactions faites par des User sur une resource.

## Which Package changed?

Please check the name of the package you changed

- [X] Components
- [ ] Core
- [ ] Icons
- [ ] Hooks

## Has the documentation changed?

- [X] Storybook

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [X] New feature (MINOR)
- [ ] Breaking change (MAJOR)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

2024-06-26 09:55 UTC, ccreusat commented on packages/react/ui/src/components/Reaction/ReactionModal.Card.tsx
> +    <div className="reaction-modal-card w-100 d-flex gap-8">
le composant Card ne peut pas être réutilisé ici ? j'ai pas le design en tête

2024-06-26 09:56 UTC, ccreusat commented on packages/react/ui/src/components/Reaction/ReactionModal.tsx
> +  const [counters, setCounters] = useState({
pas moyen de faire un petit useReducer propre pour regrouper tous les useState ?? :)

2024-06-26 09:57 UTC, ccreusat commented on packages/react/ui/src/components/Reaction/ReactionModal.tsx
> +    loadReactionDetails(resourceId, pageNumber, pageSize).then((data) => {
un petit async/await ? :D

2024-06-26 09:58 UTC, ccreusat commented on packages/react/ui/src/components/Reaction/ReactionModal.tsx
> +    loadReactionDetails(resourceId, 0, pageSize).then((data) => {
un petit async / await ? :D possible de faire une fonction et de l'appeler directement ici si asynchrone

```
useEffect(() => {
const fonction = async () => {...}
fonction()
},[])
```

2024-06-26 09:59 UTC, ccreusat commented on packages/react/ui/src/components/Reaction/ReactionModal.tsx
> +      data && setCounters(data.reactionCounters);
un seul if (data) { ... } pour regrouper les setState serait plus clean non ?

```
if (data) {
setCounters(data.reactionCounters)
setReactions(data.userReactions)
}
``` 

voire même  en profiter pour destructurer

```
if (data) {
const {reactionCounters, userReactions} = data; 

setCounters(reactionCounters)
setReactions(userReactions)
}
``` 

ou

```
const {reactionCounters, userReactions} = data; 
if (reactionCounters && userReactions) {
setCounters(reactionCounters)
setReactions(userReactions)
}
```

2024-06-26 10:00 UTC, ccreusat commented on packages/react/ui/src/components/Reaction/ReactionTypes.ts
doit être dans le composant et exporté

2024-06-26 10:00 UTC, ccreusat commented on packages/react/ui/src/components/Reaction/hook/useReactions.tsx
pas besoin de l'extension

2024-06-26 10:01 UTC, ccreusat commented on packages/react/ui/src/components/Reaction/index.ts
> +  type ReactionDetailsData,
si dans le composant, sera exporté par `export * from ""`

2024-06-26 10:01 UTC, ccreusat commented on packages/react/ui/src/core/useAvatar/useAvatar.tsx
> +      >
@jcbe-ode à voir si encore pertinent d'avoir ce que j'avais fait dans `useUser` pour récupérer l'avatar stp

2024-06-26 10:02 UTC, ccreusat requested changes
prendre en compte commentaires

2024-06-28 07:27 UTC, jcbe-ode commented on packages/react/ui/src/components/Reaction/ReactionModal.Card.tsx
> +    <div className="reaction-modal-card w-100 d-flex gap-8">
Ca n'est pas utile : la "card" ici est en lecture seule, sans interaction possible avec l'utilisateur.

2024-06-28 08:59 UTC, jcbe-ode commented on packages/react/ui/src/core/useAvatar/useAvatar.tsx
> +      >
Oui c'est probablement encore pertinent : `useUser` s'applique sur l'utilisateur **connecté**, et plus particulièrement sur son champ `picture` (provenant de la somme des infos tirées de "/userbook/api/person" et "/directory/userbook/:userId"). Or je ne sais pas quels traitements backend sont faits sur ce champ, donc je ne toucherai pas à ce code.

`useAvatar` a été conçu pour renvoyer directement l'URL de l'avatar d'un utilisateur lambda. C'est à la charge du backend de renvoyer la bonne image sur cette URL.

2024-06-28 09:12 UTC, merged