feat: #WB2-1514, add new component Treeview Sortable
edificeio/edifice-ui pull request #257
Opened 2024-10-14 13:41 UTC by Headan

# Description

Ajout d'un nouveau composant SortableTree afin de pouvoir organiser son Treeview via un draggable sur les éléments de l'arbre. 

Ticket : 

https://edifice-community.atlassian.net/browse/WB2-1514
https://edifice-community.atlassian.net/browse/WB2-1521

## Which Package changed?

Please check the name of the package you changed

- [x] Components
- [ ] Core
- [ ] Icons
- [ ] Hooks

## Has the documentation changed?

- [x] Storybook

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [x] New feature (MINOR)
- [ ] Breaking change (MAJOR)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2024-10-14 15:35 UTC, ccreusat requested changes

2024-10-14 15:35 UTC, ccreusat commented on packages/react/ui/src/components/Tree/types/types.ts
> +  indentationWidth: number;
@Headan tu peux ajouter de la JSDoc pour tous stp ?

2024-10-14 15:35 UTC, ccreusat commented on packages/react/ui/src/components/Tree/Tree.tsx
> +      // onTreeItemFold,
@Headan tu peux réactiver les 2 callbacks stp ? `onTreeItemFold` et le suivant ? tu peux les récupérer dans les props directement

2024-10-14 15:35 UTC, ccreusat commented on packages/react/ui/src/components/Tree/Tree.tsx
> +      // onTreeItemFold,
je les avais commenté, mais il les faut en fait ^^

2024-10-14 15:35 UTC, ccreusat commented on packages/react/ui/src/components/Tree/hooks/useTreeSortable.tsx
> +  const buildTree = (flatNodes: FlattenedItem[]): TreeItem[] => {
@Headan `buildTree` à mettre dans les utilitaires et à exporter stp

2024-10-14 15:35 UTC, ccreusat commented on packages/react/ui/src/components/Tree/hooks/useTreeSortable.tsx
> +  function getProjection(
ça aussi je pense que ça peut finir dans l'utilitaire sortable

2024-10-14 15:35 UTC, ccreusat commented on packages/react/ui/src/components/Tree/stories/SortableTree.stories.tsx
> +import { Meta, StoryObj } from "@storybook/react";
@Headan vu que tu as qu'une story, pas besoin de la mettre dans un dossier (ex: List, CommentProvider...)

2024-10-14 15:35 UTC, ccreusat commented on packages/react/ui/src/components/Tree/types/types.ts
> +import { UniqueIdentifier } from "@dnd-kit/core";
@Headan idem que pour la story, pas besoin de dossier

2024-10-15 10:44 UTC, ccreusat commented on packages/react/ui/src/components/Tree/hooks/useTreeSortable.tsx
> +  function getMovementAnnouncement(
à exporter  dans les utils je pense

2024-10-15 10:45 UTC, ccreusat commented on packages/react/ui/src/components/Tree/types/types.ts
> +import { UniqueIdentifier } from "@dnd-kit/core";
c'est toujours dans un dossier "types", tu as besoin que du fichier stp

2024-10-15 12:20 UTC, Headan commented on packages/react/ui/src/components/Tree/hooks/useTreeSortable.tsx
> +  function getMovementAnnouncement(
@ccreusat Il y a beaucoup de variable global utilisé dans la fonction donc je penses pas que ca soit nécessaire de le mettre dans les utils non ?

2024-10-15 12:47 UTC, merged